pull_request_rules:
  - name: Automatic merge on npm updates
    conditions:
      - author=dependabot[bot]
      - check-success=test
      - label=dependencies
    actions:
      merge:
        method: merge
